import React from "react";
import { EXAMPLE_OUTPUT } from "../data/prompts.js";

const h = React.createElement;

export default function ExampleOutput() {
  return h(
    "section",
    {
      className:
        "space-y-6 rounded-3xl border border-slate-200 bg-white/90 p-8 shadow-lg backdrop-blur",
    },
    h(
      "div",
      null,
      h("h3", { className: "text-xl font-semibold text-slate-800" }, "Example NotebookLM Output"),
      h(
        "p",
        { className: "text-xs text-slate-500 mt-1" },
        "Sample MCQ output generated by NotebookLM using the MCQ prompt template with ISTQB_CTFL_Syllabus_v4.0.1.pdf"
      )
    ),
    EXAMPLE_OUTPUT.questions.map((item, i) =>
      h(
        "div",
        {
          key: i,
          className: "rounded-2xl border border-slate-200 bg-slate-50 p-4 space-y-3",
        },
        h(
          "p",
          { className: "text-sm font-medium text-slate-800" },
          `Q${i + 1}. ${item.q}`
        ),
        h(
          "ul",
          { className: "space-y-1" },
          item.options.map((opt, j) =>
            h(
              "li",
              {
                key: j,
                className:
                  "text-sm flex gap-2 " +
                  (String.fromCharCode(65 + j) === item.answer
                    ? "text-accent font-semibold"
                    : "text-slate-600"),
              },
              h(
                "span",
                { className: "text-xs font-semibold uppercase text-slate-400 w-4 shrink-0" },
                `${String.fromCharCode(65 + j)}.`
              ),
              opt,
              String.fromCharCode(65 + j) === item.answer &&
                h("span", { className: "ml-1 text-xs" }, "✓")
            )
          )
        ),
        h(
          "div",
          { className: "rounded-2xl border border-slate-200 bg-white p-3 space-y-1" },
          h(
            "p",
            { className: "text-xs font-semibold text-accent" },
            `Answer: ${item.answer}`
          ),
          h("p", { className: "text-xs italic text-slate-500" }, item.explanation),
          h(
            "p",
            { className: "text-xs text-slate-400" },
            `Section: ${item.section}`
          )
        )
      )
    )
  );
}
